My Sample Features

My Sample - Features - My Area 0 Unsorted
	My Feature 0 Unsorted
		My Scenario 1 Sorted
			Given my step 1
			When my step 2
			Then my step 3
		My Scenario 2 Sorted
			Given my step 1
			When my step 2
			Then my step 3
		My Scenario 0 Unsorted
			Given my step 1
			When my step 2
			Then my step 3
My Sample - Features - My Area 1 All Passing
	My Feature 1 Passing
		My Scenario 1
			Given my step 1
			When my step 2 with multiline input
				Here
				 is
				 my
				 Input!
			Then my step 3 with output
		My Scenario 2
			Given my step 4
			When my step 5
			Then my step 6
		My Scenario 3
			Given my step 7
			When my step 8
			Then my step 9
	My Feature 2 Passing Partial Statement
		My Scenario 4
			Given my step 10
			When my step 11
			Then my step 12
		My Scenario 5
			Given my step 13
			When my step 14
			Then my step 15
		My Scenario 6
			Given my step 16
			When my step 17
			Then my step 18
	My Feature 3 Passing Missing Statement
		My Scenario 7
			Given my step 19
			When my step 20
			Then my step 21
		My Scenario 8
			Given my step 22
			When my step 23
			Then my step 24
		My Scenario 9
			Given my step 25
			When my step 26
			Then my step 27
	My Feature 4 Passing Reusable Steps
		My Scenario 10 With Reusable Steps
			Given you execute step 28
			When you execute step 29
			Then you execute step 30
My Sample - Features - My Area 2 Some Skipped
	My Feature 5 Some Skipped
		My Scenario 11 [Skipped - Deferred]
			Given my step 31
			When my step 32
			Then my step 33
		My Scenario 12 [Skipped - Deferred]
			Given my step 34
			When my step 35
			Then my step 36
		My Scenario 13
			Given my step 37
			When my step 38
			Then my step 39
	My Feature 6 Some Skipped
		My Scenario 14 [Skipped - Deferred]
			Given my step 40
			When my step 41
			Then my step 42
		My Scenario 15 [Skipped - Deferred]
			Given my step 43
			When my step 44
			Then my step 45
		My Scenario 16
			Given my step 46
			When my step 47
			Then my step 48
	My Feature 7 None Skipped
		My Scenario 17
			Given my step 49
			When my step 50
			Then my step 51
		My Scenario 18
			Given my step 52
			When my step 53
			Then my step 54
		My Scenario 19
			Given my step 55
			When my step 56
			Then my step 57
My Sample - Features - My Area 3 Some Failed
	My Feature 8 Some Failed
		My Scenario 20 Failed [Failed]
			Given my step 58
			When my failed step 59 [Failed]
				Error Type: Exception
				   Message: Exception of type 'System.Exception' was thrown.
				     Stack:    at MySample.Features.MyArea_3_SomeFailed.MyFeature_8_SomeFailed.<>c.<MyScenario_20_Failed>b__0_1(Step s) in C:\Users\stearm01\source\xBDD\MySample.Features\MyArea_3_SomeFailed\MyFeature_8_SomeFailed.cs:line 21
				               at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
				            --- End of stack trace from previous location where exception was thrown ---
				               at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
				            --- End of stack trace from previous location where exception was thrown ---
				               at xBDD.Core.StepExecutor.ExecuteStepAsync(Step step)
			Then my step 60 [Skipped - Previous Error]
		My Scenario 21 Failed [Failed]
			Given my step 61
			When my step 62 [Failed]
				Error Type: AggregateException
				   Message: One or more errors occurred. (My Exception)
				     Stack:    at MySample.Features.MyArea_3_SomeFailed.MyFeature_8_SomeFailed.<>c.<MyScenario_21_Failed>b__1_1(Step s) in C:\Users\stearm01\source\xBDD\MySample.Features\MyArea_3_SomeFailed\MyFeature_8_SomeFailed.cs:line 35
				               at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
				            --- End of stack trace from previous location where exception was thrown ---
				               at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
				            --- End of stack trace from previous location where exception was thrown ---
				               at xBDD.Core.StepExecutor.ExecuteStepAsync(Step step)
			Then my step 63 [Skipped - Previous Error]
		My Scenario 22 Passed
			Given my step 64
			When my step 65
			Then my step 66
	My Feature 9 Some Skipped
		My Scenario 23 Failedd [Failed]
			Given my step 67
			When my step 68 [Failed]
				Error Type: Exception
				   Message: My exception
				     Stack:    at MySample.Features.MyArea_3_SomeFailed.MyFeature_9_SomeSkipped.<>c.<MyScenario_23_Failedd>b__0_1(Step s) in C:\Users\stearm01\source\xBDD\MySample.Features\MyArea_3_SomeFailed\MyFeature_9_SomeSkipped.cs:line 21
				               at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
				            --- End of stack trace from previous location where exception was thrown ---
				               at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
				            --- End of stack trace from previous location where exception was thrown ---
				               at xBDD.Core.StepExecutor.ExecuteStepAsync(Step step)
			Then my step 69 [Skipped - Previous Error]
		My Scenario 24 Skipped [Skipped - Deferred]
			Given my step 70
			When my step 71
			Then my step 72
		My Scenario 25 Passed
			Given my step 73
			When my step 74
			Then my step 75
	My Feature 10 All Passed
		My Scenario 26 Passed
			Given my step 76
			When my step 77
			Then my step 78
		My Scenario 27 Passed
			Given my step 79
			When my step 80
			Then my step 81
		My Scenario 28 Passed
			Given my step 82
			When my step 83
			Then my step 84
My Sample - Features - My Area 4 Complete Failure
	My Feature 11 Complete Failure
		My Scenario 29 Complete Failure [Failed]
			Given my step 85
			When my failed step 86 [Failed]
				Error Type: Exception
				   Message: Exception of type 'System.Exception' was thrown.
				     Stack:    at MySample.Features.MyArea_4_CompleteFailure.MyFeature_11_CompleteFailure.<>c.<MyScenario_29_CompleteFailure>b__0_1(Step s) in C:\Users\stearm01\source\xBDD\MySample.Features\MyArea_4_CompleteFailure\MyFeature_11_CompleteFailure.cs:line 21
				               at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
				            --- End of stack trace from previous location where exception was thrown ---
				               at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
				            --- End of stack trace from previous location where exception was thrown ---
				               at xBDD.Core.StepExecutor.ExecuteStepAsync(Step step)
			Then my step 87 [Skipped - Previous Error]
My Sample - Features - My Area 5 Sort Flip
	My Feature 13 First
		My Scenario 35 Unsorted 30 Sorted
			Given my step 103 88
			When my step 104 89
			Then my step 105 90
		My Scenario 34 Unsorted 31 Sorted
			Given my step 100 91
			When my step 101 92
			Then my step 102 93
		My Scenario 33 Unsorted 32 Sorted
			Given my step 97 94
			When my step 98 95
			Then my step 99 96
	My Feature 14 Second
		My Scenario 36 Unsorted 35 Sorted
			Given my step 106 103
			When my step 107 104
			Then my step 108 105
		My Scenario 37 Unsorted 34 Sorted
			Given my step 109 100
			When my step 110 101
			Then my step 111 102
		My Scenario 38 Unsorted 33 Sorted
			Given my step 112 97
			When my step 113 98
			Then my step 114 99
	My Feature 12 Third
		My Scenario 32 Unsorted 36 Sorted
			Given my step 94 106
			When my step 95 107
			Then my step 96 108
		My Scenario 31 Unsorted 37 Sorted
			Given my step 91 109
			When my step 92 110
			Then my step 93 111
		My Scenario 30 Unsorted 38 Sorted [Failed]
			Given my step 88 112
			When my step 89 113 failed [Failed]
				Error Type: Exception
				   Message: Exception of type 'System.Exception' was thrown.
				     Stack:    at MySample.Features.MyArea_5_SortFlip.MyFeature_12_Third.<>c.<MyScenario_30_Unsorted_38_Sorted>b__0_1(Step s) in C:\Users\stearm01\source\xBDD\MySample.Features\MyArea_5_SortFlip\MyFeature_12_Third.cs:line 20
				               at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
				            --- End of stack trace from previous location where exception was thrown ---
				               at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
				            --- End of stack trace from previous location where exception was thrown ---
				               at xBDD.Core.StepExecutor.ExecuteStepAsync(Step step)
			Then my step 90 114 [Skipped - Previous Error]
My Sample - Features - My Area 6 All Skipped
	My Feature 15 All Skipped
		My Scenario 39 All Skipped [Skipped - Deferred]
			Given my step 115
			When my step 116
			Then my step 117
My Sample - Features - My Area 7 All Failed
	My Feature 16 All Failed
		My Scenario 40 Failed [Failed]
			Given my step 118
			When my step 119 failed [Failed]
				Error Type: Exception
				   Message: I failed.
				     Stack:    at MySample.Features.MyArea_7_AllFailed.MyFeature_16_AllFailed.<>c.<MyScenario_40_Failed>b__0_1(Step s) in C:\Users\stearm01\source\xBDD\MySample.Features\MyArea_7_AllFailed\MyFeature_16_AllFailed.cs:line 21
				               at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
				            --- End of stack trace from previous location where exception was thrown ---
				               at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
				            --- End of stack trace from previous location where exception was thrown ---
				               at xBDD.Core.StepExecutor.ExecuteStepAsync(Step step)
			Then my step 120 [Skipped - Previous Error]
My Sample - Features - My First Area
	My First Feature
		My First Scenario
			Given my step 1
			When my step 2
			Then my step 3
	My First Failing Feature
		My First Scenario [Failed]
			Given my step 1
			When my step 2 [Failed]
				Error Type: Exception
				   Message: My first exception.
				     Stack:    at MySample.Features.MyFirstArea.MyFirstFailingFeature.<>c.<MyFirstScenario>b__0_1(Step s) in C:\Users\stearm01\source\xBDD\MySample.Features\MyFirstArea\MyFirstFailingFeature.cs:line 24
				               at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
				            --- End of stack trace from previous location where exception was thrown ---
				               at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
				            --- End of stack trace from previous location where exception was thrown ---
				               at xBDD.Core.StepExecutor.ExecuteStepAsync(Step step)
			Then my step 3 [Skipped - Previous Error]
