Build started 9/4/2018 6:26:23 PM.
Test run for C:\Users\stearm01\source\xBDD\MySample.Features\bin\Debug\netcoreapp2.1\MySample.Features.dll(.NETCoreApp,Version=v2.1)
Microsoft (R) Test Execution Command Line Tool Version 15.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Failed   MyFirstScenario
Error Message:
 Test method MySample.Features.MyFirstArea.MyFirstFailingFeature.MyFirstScenario threw exception: 
xBDD.StepException: The step 'my step 2' threw a 'Exception' exception with a message: 'My first exception.'. See the inner exception for details. ---> System.Exception: My first exception.
Stack Trace:
    at MySample.Features.MyFirstArea.MyFirstFailingFeature.<>c.<MyFirstScenario>b__0_1(Step s) in C:\Users\stearm01\source\xBDD\MySample.Features\MyFirstArea\MyFirstFailingFeature.cs:line 24
   at xBDD.Core.StepExecutor.<>c__DisplayClass4_0.<ExecuteStepAsync>b__0() in C:\Users\stearm01\source\xBDD\xBDD\Core\StepExecutor.cs:line 25
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at xBDD.Core.StepExecutor.ExecuteStepAsync(Step step) in C:\Users\stearm01\source\xBDD\xBDD\Core\StepExecutor.cs:line 25
--- End of inner exception stack trace ---
    at xBDD.Core.StepExceptionHandler.ProcessException(StepExecutor stepExecutor, Step step, Exception ex) in C:\Users\stearm01\source\xBDD\xBDD\Core\StepExceptionHandler.cs:line 48
   at xBDD.Core.StepExceptionHandler.HandleException(StepExecutor stepExecutor, Step step, Exception ex) in C:\Users\stearm01\source\xBDD\xBDD\Core\StepExceptionHandler.cs:line 25
   at xBDD.Core.StepExecutor.ExecuteStepAsync(Step step) in C:\Users\stearm01\source\xBDD\xBDD\Core\StepExecutor.cs:line 35
   at xBDD.Core.ScenarioRunner.RunAsync(Boolean passWhenNoAction) in C:\Users\stearm01\source\xBDD\xBDD\Core\ScenarioRunner.cs:line 70
   at xBDD.Core.ScenarioBuilder.Run() in C:\Users\stearm01\source\xBDD\xBDD\Core\ScenarioBuilder.cs:line 312
   at MySample.Features.MyFirstArea.MyFirstFailingFeature.MyFirstScenario() in C:\Users\stearm01\source\xBDD\MySample.Features\MyFirstArea\MyFirstFailingFeature.cs:line 18

Standard Output Messages:
 

Debug Trace:
My First Scenario
     Given my step 1
     When my step 2
     Then my step 3



Total tests: 1. Passed: 0. Failed: 1. Skipped: 0.
Test execution time: 2.4649 Seconds

Build FAILED.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:03.42
